// Code generated by Slice Machine. DO NOT EDIT.

import HeroSlice from './HeroSlice';
import ImageGrid from './ImageGrid';
import Menu from './Menu';
import Product from './Product';
import PromoSectionSlice from './PromoSectionSlice';

export {
	HeroSlice,
	ImageGrid,
	Menu,
	Product,
	PromoSectionSlice,
};

export const components = {
	hero_slice: HeroSlice,
	image_grid: ImageGrid,
	menu: Menu,
	product: Product,
	promo_section_slice: PromoSectionSlice,
};
